[env:lilygo-tcamera-s3]
platform = espressif32@6.4.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200

lib_deps = 
    bblanchon/ArduinoJson@^6.21.5

build_flags = 
    -DBOARD_HAS_PSRAM
    -DCORE_DEBUG_LEVEL=0

board_build.partitions = huge_app.csv
board_build.arduino.memory_type = qio_opi